version: "3.4"
services:
  mongo:
    container_name: mongo
    image: 'mongo'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - ./Core/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
# networks:
#   default:
#     external:
#       name: rasa_net
