version: '3.4'

services:
  whatsappbussineesapi:
    image: whatsappbussineesapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8005:8005
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
